import Head from 'next/head'
import { MainHeader } from '../components/header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainHeader links={[{link: '/services', label: 'Servicii'}, {link: '/about', label: 'Despre noi'}]} />
      </main>
    </>
  )
}
